- scripts/play
make init - install `play` command
once installed 
`play` is available to the command line
this change makes `play` print help by default
> scripts: more play command setup - default print help

- scripts/play
include docker ids and images ids to ```play``` command for further command line development
> play: set docker ids

- GNUmakefile
> make: package-plebnet

- btcd/Dockerfile
- btcd/GNUmakefile
- btcd/docker-compose.yaml
- docker-compose.yaml
> docker-compose: add version 3.4 - avoid issue on linux

- .github/workflows/plebnet-playground.yml
- .gitignore
- .vscode/settings.json
- README.md
- bitcoin-signet/Dockerfile
- btcd/Dockerfile
- docker-compose.yaml.template
- docs/docs/index.md
- install.sh
- plebnet_generate.py
- requirements.txt
- worklogs/asherp.md
adds `plebnet_generate.py` which generates a `docker-compose.yaml` for the requested services.
usage:
```sh
python plebnet_generate.py  ARCH=aarch64-linux-gnu services=dashboard,rtl
requested services:	dashboard, rtl
required services:	bitcoind, dashboard, lnd, rtl, tor
wrote required services to docker-compose.yaml
```
> Compose template

- docs/docs/index.md
Follow up to 5e3051a7decbe07d50413a2d1c7570807bb80eeb
> make: docs - follow up

- GNUmakefile
- scripts/install-python3.8.sh
> make: install python3.8 - optional

- docker-compose.yaml.template
Submitting PR to remediate issue with css loading on browsable API pages for the LNDg dashboard.
> fix issue: missing css on browsable api

- GNUmakefile
- README.md
- docs/docs/index.md
- install.sh
add bash prompt to install.sh to alert users of a destructive event to keys
> install.sh: default is non-destructive

- GNUmakefile
some diff junk from white space removed
> make: use GIT_USER_NAME for PROFILE if $(profile) empty

- scripts/play-bitcoin
> scripts/play-bitcoin: add example play-bitcoin gettxoutsetinfo

- .github/workflows/plebnet-playground.yml
- GNUmakefile
- install.sh
- requirements.txt
- scripts/initialize
- scripts/nuke-docker
Test the install.sh script first in CI
> .github/workflows/plebnet-playground.yml: test install.sh first

- scripts/play-bitcoin
- scripts/play-lnd
play-bitcoin and play-lnd now have json docker config outputs
> scripts/play-lnd & play-bitcoin: add command outputs

- .github/workflows/plebnet-playground.yml
uses:
syphar/restore-virtualenv@v1
and
syphar/restore-pip-download-cache@v1
> .github/workflows/plebnet-playground.yml: use syphar/restore-virtualenv@v1

- docker-compose.yaml.template
- install.sh
- lnbits/.env
- lnbits/Dockerfile
- lnbits/docker-entrypoint.sh
> initial postgres + lnbits integration into plebnet docker

- scripts/play-bitcoin
match play-lnd idiom
commit:
b77de55ffac333939c352cd85d4f0ebec9000083
> play-bitcoin args

- scripts/play
match play-lnd idiom
commit:
b77de55ffac333939c352cd85d4f0ebec9000083
> play match play-lnd idiom

- GNUmakefile
make: venv: report: detect if in venv
> make: venv: report: detect if in venv

- scripts/initialize
scripts/initialize: rm docker artifacts before brew install
> scripts/initialize: rm docker artifacts before brew install

- scripts/play
tidy up scripts/play file: extraneous echo commands
> scripts/play: report NOSTR_RELAY id

- .gitmodules
- GNUmakefile
.gitmodules: nostr-rs-relay: v0.0.3
> nostr-rs-relay: bump v0.0.3

- .gitmodules
- GNUmakefile
> .gitmodules: nostr-rs-relay -> nostr/rs-relay

- GNUmakefile
> make: venv update pip

- .github/workflows/plebnet-playground.yml
- GNUmakefile
> make: docker-pull

- docker-compose.yaml.template
image: shahanafarooqui/rtl:0.13.6
> docker-compose.yaml.template: bump rtl:0.13.6

- bitcoin-signet/Dockerfile
Updated the Bitcoin Version from 24.0.1 to 25.0 in bitcoin-signet/Dockerfile
> Update Bitcoin Version to 25.0
